import express from 'express';
import { authenticateAdmin } from '../../middleware/auth.js';
import { createEvent, updateEvent, deleteEvent, listEvents, getEventById } from '../../controllers/admin/eventsAdminController.js';
const router = express.Router();
router.use(authenticateAdmin);
router.get('/', listEvents);
router.get('/:id', getEventById);
router.post('/', createEvent);
router.put('/:id', updateEvent);
router.delete('/:id', deleteEvent);
export default router;
